services:
  web:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/app
      - ./dev_test_data:/app/dev_test_data
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
