# Generated by Django 4.2.16 on 2024-09-13 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('league_lk', models.CharField(max_length=3)),
                ('team_name', models.CharField(max_length=100)),
                ('team_name_short', models.CharField(max_length=4)),
                ('team_nickname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeamAffiliate',
            fields=[
                ('nba_team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nba_data.team')),
                ('nba_abrv', models.CharField(max_length=3)),
                ('glg_team_id', models.BigIntegerField()),
                ('glg_abrv', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='GameSchedule',
            fields=[
                ('game_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('game_date', models.DateTimeField()),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='nba_data.team')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='nba_data.team')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=2)),
                ('contract_type', models.CharField(max_length=20)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_data.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_data.team')),
            ],
            options={
                'unique_together': {('team', 'player')},
            },
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineup_num', models.IntegerField()),
                ('period', models.IntegerField()),
                ('time_in', models.FloatField()),
                ('time_out', models.FloatField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_data.gameschedule')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_data.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_data.team')),
            ],
            options={
                'unique_together': {('team', 'player', 'lineup_num', 'period', 'game')},
            },
        ),
    ]
