# Generated by Django 4.2.16 on 2024-09-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamaffiliate',
            name='glg_abrv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='teamaffiliate',
            name='glg_team_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
