# Generated by Django 4.2.16 on 2024-09-18 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_data', '0002_alter_teamaffiliate_glg_abrv_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gameschedule',
            table='game_schedule',
        ),
        migrations.AlterModelTable(
            name='lineup',
            table='lineup',
        ),
        migrations.AlterModelTable(
            name='player',
            table='player',
        ),
        migrations.AlterModelTable(
            name='roster',
            table='roster',
        ),
        migrations.AlterModelTable(
            name='team',
            table='team',
        ),
        migrations.AlterModelTable(
            name='teamaffiliate',
            table='team_affiliate',
        ),
    ]
